[package]
name = "finance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "entity"]

[dependencies]
rocket = { version ="0.5.0-rc.3", features = ["secrets"] }
serde = "1.0.160"
entity = { path = "entity" }
serde_json = "1.0.96"
sqlx = {version = "0.6.3", features = ["time"]}
chrono = { version = "0.4.23", features = ["serde"] }

time = { version = "0.3.4", features = ["serde","serde-human-readable", "local-offset"] }

rust-argon2 = "1.0"
anyhow = "1.0.70"
thiserror = "1.0.48"

[dependencies.rocket_db_pools]
version = "=0.1.0-rc.3"
features = ["sqlx_mysql"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]
