[debug]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log_level = "normal"
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log_level = "critical"
limits = { forms = 32768 }


[default.databases.mysql_logs]
url = "mysql://root:root@127.0.0.1:3306/finance"

[default]
#Generate your own with the command "openssl rand -base64 32"
secret_key = ""
template_dir = "templates/"