[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
serde = "1.0.215"
rocket = { version ="0.5.1"}
sqlx = {version = "0.7.4", features = ["time"]}